### ISSUE TITLE
Add an option to create checkpoint for each player.

### ISSUE THREAD

**Issue by Drake486** [VCMP-SqMod/SqMod#10]
`SqCheckpoint.Create([CPlayer] player, [Sphere] bool, [World] int, [Vector3] vector, [Color4] color)`

Add an option to send `null` as player to create checkpoint for each player.

**Comment by iSLC** [comment]
I'm sorry what? Can you elaborate on the purpose of this request?

**Comment by Drake486** [comment]
I have created some checkpoints in my server and I use them as teleports to some inaccessible locations via foot.
Rather than creating checkpoints everytime a player joins, I would like them to be created for all players.
This feature is there in the official vcmp plugin.[http://forum.vc-mp.org/?topic=759.0](url)

**Comment by iSLC** [comment]
Show me an example from the official plugin. I can't seem to fin that particular feature there.

**Comment by Drake486** [comment]
> This feature is there in the official vcmp plugin.http://forum.vc-mp.org/?topic=759.0
> 
> _`If player is null, the checkpoint is created for all players.`_

**Comment by iSLC** [comment]
The function that was used to create checkpoints no longer accepts an `SqPlayer` instance as the first argument. And it defaults to creating the checkpoint for all players.

If you want to create a checkpoint for a specific player then use the methods from the `SqPlayer` class. They have the similar names `CreateCheckpoint(...)` and `CreateCheckpointEx(...)` and the exact same parameters. The only difference is  that this creates the checkpoint for the player managed by the class instance on which those methods were called.
