### ISSUE TITLE
split function is not working as it should.

### ISSUE THREAD

**Issue by Drake486** [VCMP-SqMod/SqMod#13]
`local test = "a, b, c, d, e";`
`local sp = split(test, ", ");`

`sp` should be equal to `["a", "b", "c", "d", "e"]` instead it is `["a", " ", "b", " ", "c", " ", "d", " ", "e"]`.

**Comment by iSLC** [comment]
This is a standard squirrel function. Therefore, if that's how it behaves then probably that's how it was meant to behave. I cannot judge how something from the Squirrel language behaves.

If you want, you could use the alternate methods that the plugin provides:

```
local exp = SqStr.Explode(',', false, "a,b,c,d,e");

foreach (k, v in exp) printf(v);

local imp = SqStr.Implode(',', exp);

print(imp);
```

However, keep in mind, that these work with character delimiters and not string delimiters. You can find more info about them on the wiki. Also, please remove the useless space after each delimiter.
