### ISSUE TITLE
PlayerPrivateMessage parameter problem.

### ISSUE THREAD

**Issue by Drake486** [VCMP-SqMod/SqMod#15]
`function onPlayerPrivateMessage(player, playerTo, message) { SqCore.SetState(0); }`

`[ERR] Squirrel exception caught (OnPlayerPrivateMessage) event`
`[INF] Message: wrong number of parameters`

**Comment by iSLC** [comment]
Is this bound globally to `SqCore` or locally on a certain player instance. Because if bound locally, then the first argument `player` is not sent.

**Comment by Drake486** [comment]
It is bound globally to `SqCore`.
`SqCore.Bind(SqEvent.PlayerPrivateMessage, this, onPlayerPrivateMessage);`
