### ISSUE TITLE
SqFind.... returns null in every case.

### ISSUE THREAD

**Issue by Drake486** [VCMP-SqMod/SqMod#16]
`SqFind.Player.NameContains(false, "partial_player_name");`

Even if the full name is used, it still returns `null`.
Not only for `.NameContains()`, it's the same for each of the available options.

`SqPlayer.Find(player_id)` works but `SqPlayer.Find(full_player_name)` returns null, again.

**Comment by iSLC** [comment]
The search is case sensitive. Be sure that the searched letters match the case of the name that is being searched. If you're looking for `abc` but your name is `aBc` then it won't match.

**Comment by Drake486** [comment]
No, it still fails to return the correct player entity and returns `null` in every case.
