### ISSUE TITLE
Add (header, payload) parameters to SqPlayer.TrackPosition.

### ISSUE THREAD

**Issue by Drake486** [VCMP-SqMod/SqMod#18]
Syntax: `SqPlayer.TrackPosition(number_of_position_changes, header, payload);`
Event: `PlayerPosition(player, header, payload);`

Example of usage:
`player.TrackPosition(1, 1, "cmd_heal");`

`function onPlayerPosition(player, header, payload)`
`{`
`if(payload == "cmd_heal") player.Message("Healing failed.");`
`}`

**Comment by iSLC** [comment]
Added the method except it's named `SetTrackPosition(number_of_position_changes, header, payload)` to not interfere with the name of the property which ignores the header/payload.

Also, the specified header and payload will be sent continuously. So you should not expect that the next time the event is called that header/payload is 0/null but instead what you set them to be.

So if you don't want the same header and payload to be received next time, be sure to clean them up manually:

```
function onPlayerPosition(player, header, payload)
{
    player.SetTrackPosition(player.TrackPosition, 0, null);
}
```
