### ISSUE TITLE
Add a function to get the list of commands as string and array.

### ISSUE THREAD

**Issue by Drake486** [VCMP-SqMod/SqMod#19]
Syntax: 
`SqCommand.List();`           // Should return a string with all the commands.
`SqCommand.Collect();`     // Should return an array with all the commands.

Example of usage:
`print(SqCommand.List());`
`print(SqCommand.Collect());`

Output:
`cmd1, cmd2, cmd3,.....`
`["cmd1", "cmd2", "cmd3",....]`

**Comment by iSLC** [comment]
I haven't added a method to create them as a list in a string but I've added the means necessary to achieve it by script.

The two new methods of the command manager to obtain all command listeners as some sort of list:

```
local array_of_listeners = mycmdmanager.GetArray();
local table_of_listeners = mycmdmanager.GetTable();
```

The benefits of each is that the array will contain them in the same order as the manager stores them, whereas the table might sort them by name. Also, the array could also have them sorted by name if before retrieving them, the `Sort()` methods is called on the manager.

The third method is to iterate all command listeners with a callback:

```
local str = "";
mycmdmanager.Foreach(this, function(listener) {
    str += listener.Name;
    str += ", ";
});
```
