### ISSUE TITLE
Improvement on SqForeach

### ISSUE THREAD

**Issue by rasikhq** [VCMP-SqMod/SqMod#29]
Adding support for 'continue' like behavior.

SqForeach.Player.Active( function( this, pPlayer ) {
    if( !pPlayer.Spawned ) return true; // Works as continue like in native foreach
    return false; // Works as break like in native foreach
} );

**Comment by iSLC** [comment]
The feature was implemented. You can either return nothing, `null`,  `true` or something that evaluates to `true` in order to continue. Or something that evaluates to `false` in order to stop. The implementation was not tested. Although it should work in theory.
