### ISSUE TITLE
Unable to select() on IRC session

### ISSUE THREAD

**Issue by Luckshya** [VCMP-SqMod/SqMod#32]
While closing the server in linux with CTRL+C `[ERR] Unable to select() on IRC session` appears and then it gets freezed and nothing happens. I have to kill the screen or close the ssh session to close the server.
Also, it happens sometimes but most of the times.

**Comment by iSLC** [comment]
I have no idea what's wrong with this one and the IRC module is already on life support and one bad encounter away from being deprecated.
