### ISSUE TITLE
resultset.FieldsTable only returns null

### ISSUE THREAD

**Issue by OmairMunir0** [VCMP-SqMod/SqMod#35]
Code used: https://pastebin.com/EePCSc5L
Output: https://i.imgur.com/ykaftWf.png

Doesn't happen in .GetField or .FieldsArray, only .FieldsTable is being buggy for some reason.
Using the plugin on Windows 7 x64 (04rel006)

**Comment by iSLC** [comment]
First one should be fixed by: bfdb042442c4bd9453a8668dc900acfa59873d42
Second one should be fixed by: 3a5563820ddfd6f5157aefb901f873b93c5f0ae0

I'll be closing this for now. Let me know if the problem persists and thanks for the report.
