### ISSUE TITLE
Suggestion - Allow changing pos on blip

### ISSUE THREAD

**Issue by ImHiki** [VCMP-SqMod/SqMod#41]
blip.Pos = Vector3( xx, xx, xx )
so you dont need delete and re create blip to changing pos

**Comment by iSLC** [comment]
Server does not support provide this feature. As can be observed from the provided API https://github.com/iSLC/VCMP-SqMod/blob/master/include/vcmp.h#L369

You can only create or delete blips. Nothing else can be changed about them because they're immutable.

**Comment by iSLC** [comment]
Closing this untill a solution is provided.
