### ISSUE TITLE
[ERR] Error on CGameplay::onReceiveClientData, [String of size (39807) starting at (6) is out of buffer capacity (512)]

### ISSUE THREAD

**Issue by ImHiki** [VCMP-SqMod/SqMod#42]
it happen randomly

**Comment by iSLC** [comment]
That's quite simple to understand. You're trying to read a string of 39807 characters (i.e 39807 bytes in size) starting at byte 6 from a buffer of 512 bytes total size.

Translation, you're trying to read 39807 bytes from a buffer of 512 bytes. See the issue?

Validate your stream data to make sure you read it in the correct order and matching values.

Last but not least, include a script that replicates the issue. Without that, it can be ruled as a mistake on your end.

**Comment by rasikhq** [comment]
This is most likely a wrong order read

**Comment by iSLC** [comment]
Closing this due to lack of feedback.
