### ISSUE TITLE
`make` doesn't create output folders

### ISSUE THREAD

**Issue by dracc** [VCMP-SqMod/SqMod#43]
Cloning and building this project for the first time is rendered a pain as `Makefile` doesn't include any instructions to create the output folders.

Environment:
Debian GNU/Linux testing
gcc 8.3.0
g++ 8.3.0
GNU make 4.2.1<hr>

Edit: After reading through `Makefile` it became apparent that `make all` or `make folders` would create all necessary folders.
Easy fix for this issue would be to move https://github.com/iSLC/VCMP-SqMod/blob/d3e6adea147f5b2cae5119ddd6028833aa625c09/Makefile#L192 to line 147.

**Comment by iSLC** [comment]
If you have a suggestion that you can implement then feel free to create a pull request.
