### ISSUE TITLE
Crashing while closing/reloading the server when there are vehicle entities present.

### ISSUE THREAD

**Issue by Drake486** [VCMP-SqMod/SqMod#9]
Probable cause would be in the destruction method of the vehicle entity while closing/reloading the server.

**Comment by iSLC** [comment]
From my experience this wold be the server that's actually crashing. Either a poor management on their part or who knows.

You'll need to come up with an example that replicates the issue to know that this is in fact caused by the plugin.

**Comment by Drake486** [comment]
Just create a vehicle and try to close/reload the server.

**Comment by Drake486** [comment]
Now the vehicle entities are not removed at all, resulting in recreation of the vehicles after every reload.
